### ISSUE TITLE
Add pa11y-ci

### ISSUE THREAD

**Issue by grayside** [phase2/docker-pa11y#5]
[pa11y-ci](https://github.com/pa11y/pa11y-ci) adds some really nice functionality for aggregating test runs across multiple sites. We should add it to the container as this kind of approach is essential.

pa11y-ci is not yet ported to pa11y v5, and uses pa11y itself as a dependency. Do we have duplicate code in the image? Do we have multiple images? Do we find a way to use whatever pa11y version pa11y-ci pulls in? I'm partial to the middle answer:

Replacing the existing versioning with something more like this:

```
outrigger/pa11y:5
outrigger/pa11y:5ci
```

Once this is in, we can follow-up by adding a custom reporter, such as https://github.com/tjheffner/vue-pa11y.

**Comment by grayside** [comment]
Looks like pa11y-ci had a 2.0 release just 2 days ago with pa11y v5 support.

**Comment by tjheffner** [comment]
pa11y-ci added here https://github.com/phase2/docker-pa11y/pull/7 . keeps pa11y as well, which gives users the option to pass either `pa11y` or `pa11y-ci` as the command to the service using the image.

```
report:
  image: outrigger/pa11y
  container_name: project_${DOCKER_ENV:-local}_pa11y
  command: bash -c "pa11y-ci --json > report.json"
  network_mode: bridge
  cap_add:
    - SYS_ADMIN
volumes:
  - ./test/pa11y:/app

```
then `docker-compose run --rm report` will generate a report.json in test/pa11y that can be used by another service (say, something hosting the parsed dashboard report)
